apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-deployment
          image: nicktehrany/wdm-cassandra-microservices:order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB
              value: "cassandra"
            - name: STOCK_SERVICE
              value: "http://stock-service"
            - name: PAYMENT_SERVICE
              value: "http://payment-service"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
spec:
  type: NodePort
  selector:
    app: order-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-ingress
  labels:
    name: order-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /orders
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/orders"
            backend:
              service:
                name: order-service
                port:
                  number: 80
