apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-deployment
          image: nicktehrany/wdm-cassandra-microservices:payment-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB
              value: "cassandra"
            - name: ORDER_SERVICE
              value: "http://order-service"
            - name: STOCK_SERVICE
              value: "http://stock-service"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
  labels:
    name: payment-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /payment
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: payment-service
                port:
                  number: 80
