kind: Pod
apiVersion: v1
metadata:
  name: payment-service

spec:
  containers:
    - name: payment-service
      image: nicktehrany/wdm-cassandra-microservices:payment
      imagePullPolicy: IfNotPresent
