apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  labels:
    name: stock-deployment
spec:
  selector:
    matchLabels:
      app: stock-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-deployment
    spec:
      containers:
        - name: stock-deployment
          image: nicktehrany/wdm-cassandra-microservices:stock-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB
              value: "cassandra"
            - name: ORDER_SERVICE
              value: "http://order-service"
            - name: PAYMENT_SERVICE
              value: "http://payment-service"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  labels:
    name: stock-service
spec:
  type: NodePort
  selector:
    app: stock-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-ingress
  labels:
    name: stock-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /stock
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: stock-service
                port:
                  number: 80
